version: '3.7'

services:
  web-api-v2:
    build: .
    restart: always
    volumes:
      - ./app/:/app/app/
      - ./server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./server/gunicorn_conf.py:/gunicorn_conf.py
      - ./server/upload.nginx:/etc/nginx/conf.d/upload.conf
      - ./server/engine.nginx:/etc/nginx/conf.d/engine.conf
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: 1
      API_ENV: DEVELOPMENT
      FLASK_ENV: DEVELOPMENT

  storage-api-v2:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
    - 10000:10000
    - 10001:10001
    - 10002:10002
  
  db-api-v2:
    image: postgres:alpine
    restart: always
    ports:
    - 5432:5432
    volumes: 
    - ./test/sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: tester