name: Deploy APIv2 to Sandbox Environment

on:
 push:
  branches:
   - sandbox

jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy APIv2 to Sandbox Environment
  environment: sandbox

## declares credentials for Azure Container Registry!!
  steps:
  - name: Login to Azure Container Registry
    uses: azure/docker-login@v1
    with:
      login-server: c19dashacrprod.azurecr.io
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}

   
  - name: Deploy Container to Azure App Services
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'c19dashsbuksfe01apiv2server'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      images: 'c19dashacrprod.azurecr.io/apiv2server:26909-development'
    